export const BOT_ROSTER = [
  {
    id: 'ray',
    name: 'Rookie Ray',
    rating: 180,
    difficulty: 'easy',
    label: 'Easy',
    tagline: 'Warm-up bot',
    description: 'Misses tons of turns and takes forever to spot free squares.',
    accent: '#7dd3fc',
    panel: '#eff8ff',
    moveChance: 0.16,
    delay: 1180,
  },
  {
    id: 'milo',
    name: 'Mellow Milo',
    rating: 320,
    difficulty: 'easy',
    label: 'Easy',
    tagline: 'Chill bot',
    description: 'Gets distracted often, but sneaks in a correct answer now and then.',
    accent: '#86efac',
    panel: '#f3fff6',
    moveChance: 0.26,
    delay: 1080,
  },
  {
    id: 'piper',
    name: 'Puzzle Piper',
    rating: 620,
    difficulty: 'medium',
    label: 'Medium',
    tagline: 'Steady bot',
    description: 'Keeps a solid pace, but still has enough pauses to let you breathe.',
    accent: '#f9a8d4',
    panel: '#fff3f9',
    moveChance: 0.46,
    delay: 920,
  },
  {
    id: 'juno',
    name: 'Juno Grid',
    rating: 780,
    difficulty: 'medium',
    label: 'Medium',
    tagline: 'Balanced bot',
    description: 'Usually finds the clean square, but drops tempo more often now.',
    accent: '#c4b5fd',
    panel: '#f7f3ff',
    moveChance: 0.5,
    delay: 860,
  },
  {
    id: 'theo',
    name: 'Tactician Theo',
    rating: 1080,
    difficulty: 'hard',
    label: 'Hard',
    tagline: 'Sharp bot',
    description: 'Sharp enough to feel dangerous, but no longer sprints the whole board.',
    accent: '#fca5a5',
    panel: '#fff3f2',
    moveChance: 0.68,
    delay: 660,
  },
  {
    id: 'mira',
    name: 'Blitz Mira',
    rating: 1260,
    difficulty: 'hard',
    label: 'Hard',
    tagline: 'Aggro bot',
    description: 'Plays quickly, though her momentum now breaks often enough to catch.',
    accent: '#fdba74',
    panel: '#fff7ef',
    moveChance: 0.74,
    delay: 560,
  },
  {
    id: 'vega',
    name: 'Oracle Vega',
    rating: 1620,
    difficulty: 'insane',
    label: 'Insane',
    tagline: 'Elite bot',
    description: 'Still elite, but now blinks enough that a clean solve can beat it.',
    accent: '#a5b4fc',
    panel: '#f2f4ff',
    moveChance: 0.84,
    delay: 450,
  },
  {
    id: 'zero',
    name: 'Titan Zero',
    rating: 1980,
    difficulty: 'insane',
    label: 'Insane',
    tagline: 'Monster bot',
    description: 'Still scary, but no longer perfect. You can win if you stay sharp.',
    accent: '#f87171',
    panel: '#fff1f1',
    moveChance: 0.9,
    delay: 390,
  },
];

export function getBotById(botId) {
  return BOT_ROSTER.find((bot) => bot.id === botId) ?? BOT_ROSTER[0];
}
